import type { Metadata } from "next";
import { albert_sans, inter, nunito_sans } from "./fonts";
import "./globals.css";
import { Providers } from "./providers";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${albert_sans.variable} ${nunito_sans.variable} ${inter.variable} antialiased min-h-screen h-fi`}
      >
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
